### ISSUE TITLE
macOS error: socks5 proxy addr

### ISSUE THREAD

**Issue by AiziChen** [heiher/hev-socks5-server#19]
在macOS平台上编译并运行，会提示："[E] socks5 proxy addr"
我用perror函数打印这个错误，会显示：`Protocol not supported`
我将ai_protocol设为0，错误同样还在。

![6869847A-2440-49C5-AB49-1A103ECBF189](https://user-images.githubusercontent.com/7786058/122640287-5d121180-d131-11eb-8a11-c2493adfde30.png)

**Comment by heiher** [comment]
贴下配置文件的内容。

**Comment by AiziChen** [comment]
```yaml
main:
  # Worker threads
  workers: 4
  # Listen port
  port: 1081
  # Listen address (ipv4|ipv6)
  listen-address: '::'

auth:
  username: quanye
  password: quanyec

misc:
   # task stack size (bytes)
  task-stack-size: 8192
   # connect timeout (ms)
  connect-timeout: 5000
   # read-write timeout (ms)
  read-write-timeout: 60000
   # stdout, stderr or file-path
  log-file: stderr
   # debug, info, warn or error
  log-level: debug
   # If present, run as a daemon with this pid file
#  pid-file: /run/hev-socks5-server.pid
   # If present, set rlimit nofile; else use default value
  limit-nofile: 1024
```
