### ISSUE TITLE
socks5用户名密码无需验证

### ISSUE THREAD

**Issue by hihibb3312** [heiher/hev-socks5-server#58]
无论是使用auth.txt还是在main.yml里配置用户名密码。客户端输入任何用户名密码或者不输入都可以成功连接，我的配置文件格式是这样的。使用的是released里的arm32 linux 版本
```
main:
  # Worker threads
  workers: 1
  # Listen port
  port: 55555
  # Listen address (ipv4|ipv6)
  listen-address: '0.0.0.0'
  # UDP listen port
  udp-port: 55555
  # UDP listen address (ipv4|ipv6)
# udp-listen-address: '::1'
  # Listen ipv6 only
  listen-ipv6-only: false
  # Bind source address (ipv4|ipv6)
  bind-address: '0.0.0.0'
  # Domain address type (ipv4|ipv6|unspec)
  domain-address-type: unspec

auth:
  #file: conf/auth.txt
  username: 'dd'
  password: 'testtest'

```
